### ISSUE TITLE
ドメインが失効していませんか？

### ISSUE THREAD

**Issue by yanorei32** [hakka-ch/hakka.ch#20]
SSIA.

```
C:\Users\ray>nslookup hakka.ch
Server:  one.one.one.one
Address:  2606:4700:4700::1111

*** one.one.one.one can't find hakka.ch: Non-existent domain

C:\Users\ray>
```

**Comment by 6h1sa** [comment]
うっかりしていて更新に失敗して、失効している状態です……
Redemption Grace Period に入ってしまっており、復旧には時間がかかりそうです……

**Comment by yanorei32** [comment]
レジストラにはよりますが、Redemption Grace Periodの内なら、通常の延長か購入に近いインターフェースで延長できるはずです（？）。
ので、Redemption Grace Periodが過ぎない内に取り返したほうが良さそうです。

**Comment by 6h1sa** [comment]
namecheap で管理しているのですが、250ドルの償還手数料と更新料18.98ドルで手元に戻せるみたいです。namecheap のサポートへの連絡が必要っぽいので、やや時間がかかりそうです（ミスとはいえ悩む程度の手数料がかかるのも問題）

**Comment by yanorei32** [comment]
うーむなるほど厳しい…

**Comment by 6h1sa** [comment]
とりあえず30日間はRGPの期間らしいので、金の問題が解決したら更新します

**Comment by 6h1sa** [comment]
ドメインが復活しました
